<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1</TargetFrameworks>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
    <IncludeSourceRevisionInInformationalVersion>true</IncludeSourceRevisionInInformationalVersion>
    <AssemblyName>StrmLiteAssistant</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Properties\thumb.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="mediabrowser.server.core" Version="4.9.1.90" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
